services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-converter
    volumes:
      - cohort-15-data-science:/notebooks
    ports:
      - "8889:8889"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["bash", "-c", "while true; do sleep 30; done;"]

volumes:
  cohort-15-data-science:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD
