version: "3"

services:
  jupyter:
    container_name: jpynbook
    image: jpynbook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - cohort-15-data-science:/notebooks
    environment:
      - GRANT_SUDO=yes
    user: root

volumes:
  cohort-15-data-science:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rsbiim/Code/Projects/cohort-15-data-science
